name: PVPPlugin
version: 1.0
main: com.example.pvpplugin.PVPPlugin
api-version: 1.16
author: YourName
description: 마인크래프트 PVP 플러그인

commands:
  game:
    description: 게임 관리 명령어
    usage: /game <start|reset>
    permission: pvp.admin
    permission-message: "§c이 명령어를 사용할 권한이 없습니다!"

permissions:
  pvp.admin:
    description: 게임 관리 권한
    default: op
